#' Length Function
#'
#' @param n is the value of the initial lengeth you want to convert
#' @param from the units of the initial values, inch= inches, cm = centemeters, m = meter, km = kilometer, mm = milimeter, mile = mile, yd = yards, ft = foot, microm = micrometer, nm = nanometer
#' @param to the units you want to convert to
#'
#' @return the value of the conversion in the units of "to"
#' @export
#'
#' @examples length_conv(5,"yd","mile"),
#' length_conv(23, "mile", "nm")

length_conv <- function(n, from, to) {
  if(from=="inch"){
    if(to=="cm")
      return(n*2.54)
    }
  if(from=="inch"){
    if(to=="m")
      return(n*.0254)
  }
  if(from=="inch"){
    if(to=="km")
      return(n*.0000254)
  }
  if(from=="inch"){
    if(to=="mm")
      return(n*25.4)
  }
  if(from=="inch"){
    if(to=="mile")
      return(n*.000015783)
  }
  if(from=="inch"){
    if(to=="yd")
      return(n*.0277778)
  }
  if(from=="inch"){
    if(to=="ft")
      return(n*.083333)
  }
  if(from=="inch"){
    if(to=="microm")
      return(n*25400)
  }
  if(from=="inch"){
    if(to=="nm")
      return(n*25400000)
  }
  #all the functions starting with inch above

  if(from=="cm"){
    if(to=="inch")
      return(n*0.39370)
  }
  if(from=="cm"){
    if(to=="m")
      return(n*0.01)
  }
  if(from=="cm"){
    if(to=="km")
      return(n*.00001)
  }
  if(from=="cm"){
    if(to=="mm")
      return(n*10)
  }
  if(from=="cm"){
    if(to=="mile")
      return(n*.0000062137)
  }
  if(from=="cm"){
    if(to=="yd")
      return(n*.0109361)
  }
  if(from=="cm"){
    if(to=="ft")
      return(n*.0328084)
  }
  if(from=="cm"){
    if(to=="microm")
      return(n*10000)
  }
  if(from=="cm"){
    if(to=="mile")
      return(n*10000000)
  }
  #all the functions from cm above
  if(from=="m"){
    if(to=="inch")
      return(n*39.370)
  }
  if(from=="m"){
    if(to=="cm")
      return(n*100)
  }
  if(from=="m"){
    if(to=="km")
      return(n*.001)
  }
  if(from=="m"){
    if(to=="mm")
      return(n*1000)
  }
  if(from=="m"){
    if(to=="mile")
      return(n*.00062137)
  }
  if(from=="m"){
    if(to=="yd")
      return(n*1.09361)
  }
  if(from=="m"){
    if(to=="ft")
      return(n*3.28084)
  }
  if(from=="m"){
    if(to=="microm")
      return(n*1000000)
  }
  if(from=="m"){
    if(to=="nm")
      return(n*1000000000)
  }
  #all the functions from m above
  if(from=="km"){
    if(to=="inch")
      return(n*39370.1)
  }
  if(from=="km"){
    if(to=="cm")
      return(n*100000)
  }
  if(from=="km"){
    if(to=="m")
      return(n*1000)
  }
  if(from=="km"){
    if(to=="mm")
      return(n*1000000)
  }
  if(from=="km"){
    if(to=="mile")
      return(n*.62137)
  }
  if(from=="km"){
    if(to=="yd")
      return(n*1093.61)
  }
  if(from=="km"){
    if(to=="ft")
      return(n*3280.84)
  }
  if(from=="km"){
    if(to=="microm")
      return(n*1000000000)
  }
  if(from=="km"){
    if(to=="nm")
      return(n*1000000000000)
  }
  #all the functions from km above
  if(from=="mm"){
    if(to=="inch")
      return(n*.0393701)
  }
  if(from=="mm"){
    if(to=="cm")
      return(n*.1)
  }
  if(from=="mm"){
    if(to=="m")
      return(n*.001)
  }
  if(from=="mm"){
    if(to=="km")
      return(n*.000001)
  }
  if(from=="mm"){
    if(to=="mile")
      return(n*.00000062137)
  }
  if(from=="mm"){
    if(to=="yd")
      return(n*.00109361)
  }
  if(from=="mm"){
    if(to=="ft")
      return(n*.00328084)
  }
  if(from=="mm"){
    if(to=="microm")
      return(n*1000)
  }
  if(from=="mm"){
    if(to=="nm")
      return(n*1000000)
  }
  #all functions from mm above
  if(from=="mile"){
    if(to=="inch")
      return(n*63360)
  }
  if(from=="mile"){
    if(to=="cm")
      return(n*160934)
  }
  if(from=="mile"){
    if(to=="m")
      return(n*1609.34)
  }
  if(from=="mile"){
    if(to=="km")
      return(n*1.60934)
  }
  if(from=="mile"){
    if(to=="mm")
      return(n*1609000)
  }
  if(from=="mile"){
    if(to=="yd")
      return(n*.1760)
  }
  if(from=="mile"){
    if(to=="ft")
      return(n*5280)
  }
  if(from=="mile"){
    if(to=="microm")
      return(n*1609000000)
  }
  if(from=="mile"){
    if(to=="nm")
      return(n*1609000000000)
  }
  #all functions from mile above
  if(from=="yd"){
    if(to=="inch")
      return(n*36)
  }
  if(from=="yd"){
    if(to=="cm")
      return(n*91.44)
  }
  if(from=="yd"){
    if(to=="m")
      return(n*.9144)
  }
  if(from=="yd"){
    if(to=="km")
      return(n*.0009144)
  }
  if(from=="yd"){
    if(to=="mm")
      return(n*914.4)
  }
  if(from=="yd"){
    if(to=="mile")
      return(n*.000568182)
  }
  if(from=="yd"){
    if(to=="ft")
      return(n*3)
  }
  if(from=="yd"){
    if(to=="microm")
      return(n*914400)
  }
  if(from=="yd"){
    if(to=="nm")
      return(n*914400000)
  }
  #all functions from yd above
  if(from=="ft"){
    if(to=="inch")
      return(n*12)
  }
  if(from=="ft"){
    if(to=="cm")
      return(n*30.48)
  }
  if(from=="ft"){
    if(to=="m")
      return(n*.3048)
  }
  if(from=="ft"){
    if(to=="km")
      return(n*.0003048)
  }
  if(from=="ft"){
    if(to=="mm")
      return(n*304.8)
  }
  if(from=="ft"){
    if(to=="mile")
      return(n*.000189394)
  }
  if(from=="ft"){
    if(to=="yd")
      return(n*.33333)
  }
  if(from=="ft"){
    if(to=="microm")
      return(n*304800)
  }
  if(from=="ft"){
    if(to=="nm")
      return(n*304800000)
  }
  #all functions coming from ft above
  if(from=="microm"){
    if(to=="inch")
      return(n*.0000393701)
  }
  if(from=="microm"){
    if(to=="cm")
      return(n*.0001)
  }
  if(from=="microm"){
    if(to=="m")
      return(n*.000001)
  }
  if(from=="microm"){
    if(to=="km")
      return(n*.000000001)
  }
  if(from=="microm"){
    if(to=="mile")
      return(n*.00000000062137)
  }
  if(from=="microm"){
    if(to=="yd")
      return(n*.00000109361)
  }
  if(from=="microm"){
    if(to=="ft")
      return(n*.00000328084)
  }
  if(from=="microm"){
    if(to=="mm")
      return(n*.001)
  }
  if(from=="microm"){
    if(to=="nm")
      return(n*1000000)
  }
  #all functions from microm above
  if(from=="nm"){
    if(to=="inch")
      return(n*.0000000393701)
  }
  if(from=="nm"){
    if(to=="cm")
      return(n*.0000001)
  }
  if(from=="nm"){
    if(to=="m")
      return(n*.000000001)
  }
  if(from=="nm"){
    if(to=="km")
      return(n*.000000000001)
  }
  if(from=="nm"){
    if(to=="mile")
      return(n*.00000000000062137)
  }
  if(from=="nm"){
    if(to=="yd")
      return(n*.00000000109361)
  }
  if(from=="nm"){
    if(to=="ft")
      return(n*.00000000328084)
  }
  if(from=="nm"){
    if(to=="mm")
      return(n*.000001)
  }
  if(from=="nm"){
    if(to=="microm")
      return(n*.001)
  }
}

